In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7390, 4977, 9288, 8486],
 [7390, 4977, 9288, 4550],
 [7390, 8437, 9288, 1655],
 [6549, 8257, 217, 910, 6413],
 [6549, 8257, 217, 910, 7637],
 [4207, 7390, 4678, 9288, 5465],
 [2313, 19, 9615, 910]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7390 4977 9288 8486]
 [   0    0    0    0 7390 4977 9288 4550]
 [   0    0    0    0 7390 8437 9288 1655]
 [   0    0    0 6549 8257  217  910 6413]
 [   0    0    0 6549 8257  217  910 7637]
 [   0    0    0 4207 7390 4678 9288 5465]
 [   0    0    0    0 2313   19 9615  910]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\lenovo\Desktop\project\rnnclassification\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 263ms/step


array([[[-4.07784805e-02,  3.31301801e-02,  1.46454908e-02,
          6.62273169e-03, -3.40148807e-02,  1.56197697e-03,
         -9.03628767e-04,  4.76447083e-02, -1.97619088e-02,
         -7.34914094e-04],
        [-4.07784805e-02,  3.31301801e-02,  1.46454908e-02,
          6.62273169e-03, -3.40148807e-02,  1.56197697e-03,
         -9.03628767e-04,  4.76447083e-02, -1.97619088e-02,
         -7.34914094e-04],
        [-4.07784805e-02,  3.31301801e-02,  1.46454908e-02,
          6.62273169e-03, -3.40148807e-02,  1.56197697e-03,
         -9.03628767e-04,  4.76447083e-02, -1.97619088e-02,
         -7.34914094e-04],
        [-4.07784805e-02,  3.31301801e-02,  1.46454908e-02,
          6.62273169e-03, -3.40148807e-02,  1.56197697e-03,
         -9.03628767e-04,  4.76447083e-02, -1.97619088e-02,
         -7.34914094e-04],
        [ 3.26119326e-02, -2.92185191e-02, -2.65666842e-02,
          1.64774545e-02,  1.72904171e-02,  4.90461849e-02,
         -2.62638573e-02,  3.20252888e-02, -2.411922

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 7390, 4977, 9288, 8486])

In [15]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None